###
POST  http://localhost:3001/api/users
Content-Type: application/json

{
    "username":"john123",
    "name":"john",
    "password":"bus"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"john123",
    "password":"bus"
}

###
GET http://localhost:3001/api/users

